"""Add department, level, semester to Course model with data handling

Revision ID: 0af5d51e8c6f
Revises: 179c846f521f
Create Date: 2025-06-16 06:56:22.465912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af5d51e8c6f'
down_revision = '179c846f521f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        # Step 1: Add new columns as NULLABLE first
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.String(length=50), nullable=True))

    # Step 2: Populate existing rows with a default value for the new columns
    # This is crucial for existing data that would otherwise be NULL
    op.execute("UPDATE courses SET department = 'Computer Engineering' WHERE department IS NULL;")
    op.execute("UPDATE courses SET level = 'Level 400' WHERE level IS NULL;")
    op.execute("UPDATE courses SET semester = 'Second Semester' WHERE semester IS NULL;")
    # Feel free to adjust these default values ('General', 'Level 100', 'First Semester')
    # to something more appropriate for your existing data if needed.

    with op.batch_alter_table('courses', schema=None) as batch_op:
        # Step 3: Now alter columns to NOT NULL
        batch_op.alter_column('department',
                   existing_type=sa.String(length=100),
                   nullable=False)
        batch_op.alter_column('level',
                   existing_type=sa.String(length=50),
                   nullable=False)
        batch_op.alter_column('semester',
                   existing_type=sa.String(length=50),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('semester')
        batch_op.drop_column('level')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
