"""Add verified_by_face column to AttendanceRecord model

Revision ID: 16a274d029b1
Revises: 0af5d51e8c6f
Create Date: 2025-06-26 08:25:30.241030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a274d029b1'
down_revision = '0af5d51e8c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by_face', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_column('verified_by_face')

    # ### end Alembic commands ###
