"""Add password column to lecturers table

Revision ID: 8519f1cc51c8
Revises: bf152323869f
Create Date: 2025-06-11 19:11:56.703418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8519f1cc51c8'
down_revision = 'bf152323869f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
