"""Initialize migrations

Revision ID: bf152323869f
Revises: 
Create Date: 2025-06-11 10:55:31.458716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf152323869f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('attendance_reports')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('attendance_exceptions', schema=None) as batch_op:
        batch_op.alter_column('attendance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('updated_status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('matricule',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('lecturer_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('matricule',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('face_records', schema=None) as batch_op:
        batch_op.alter_column('matricule',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('face_embedding',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('face_records', schema=None) as batch_op:
        batch_op.alter_column('face_embedding',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.alter_column('matricule',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('matricule',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('lecturer_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('matricule',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('attendance_exceptions', schema=None) as batch_op:
        batch_op.alter_column('updated_status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('attendance_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('attendance_reports',
    sa.Column('report_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('generated_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], name=op.f('attendance_reports_course_code_fkey')),
    sa.PrimaryKeyConstraint('report_id', name=op.f('attendance_reports_pkey'))
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('notifications_pkey'))
    )
    # ### end Alembic commands ###
